<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "azgr_downloadcenter"
 *
 * Auto generated by Extension Builder 2016-10-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Downloadcenter',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Bernhard Schütz',
    'author_email' => 'schuetz@azurgruen.de',
    'dependencies' => 'extbase,fluid,vhs',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
            'vhs' => ''
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
